### ISSUE TITLE
Repeat information on each page

### ISSUE THREAD

**Issue by kjones13** [NEONInc/neonPhenoSheetGenerator#2]
Hi Christine. In the recent data entry frenzy it was clear that having some information repeated on each datasheet was key to dealing with datasheets filed out of order or incompletely scanned. Specifically we need the ability to have:
* site
* date
* page x of n

on each page. I don't totally understand Shiny yet and only have a basic grasp on LaTeX so I will not monkey with your code but I did find a couple resources that may have useful information.

1. the fancyhdr package (http://tex.stackexchange.com/questions/109656/same-header-and-footer-for-every-page)
2. options for repeating part of a document (http://tex.stackexchange.com/questions/147376/repeating-part-of-document-on-every-page)

Not sure if these have what you need but I'm happy to help troubleshoot once I have a little better understanding of Shiny (following our journal club intro).
Cheers.

**Comment by chrlaney** [comment]
Hi Katie - I will try to work on this tomorrow. Thanks for doing some research for me!

**Comment by chrlaney** [comment]
@kjones13 Unfortunately this is a difficult request to resolve. For now, can your techs just write site, date, and page x of n on the pages when they print them out?

**Comment by chrlaney** [comment]
@kjones13 Found a method to repeat header on each page and include a Page x of n at the bottom of each page. Development version of app is at https://claney.shinyapps.io/neonPhenoSheetGenerator_dev/. Please give it a try with a few datasets. It works with long datasets, and fills in all of the appropriate fields with every test dataset I have except for the one you just sent me. May need to discuss.

**Comment by kjones13** [comment]
It worked with the one I just tried and looks really fantastic! The page breaks and numbering are a little off, it looks like page breaks are pre-set at x number of rows but then get off when the phenophase desc. column wraps within the cell. This could simply be a column width issue. Remarks can be as small as necessary, we generally want to discourage use of the remarks field anyway, plus, we can always add a supplemental datasheet for recording remarks if we need.

I'm not sure why but it appears that columns in the file I sent you are in a different order than in other files and there is a blank column. If your code is referencing the column index rather than the header, this may partially explain the issue but there are formatting differences too (e.g. bold text). ??

I promise I didn't intentionally send you a screwy dataset, just picked one from a long list.

**Comment by chrlaney** [comment]
Interesting - could you please upload several real datasets collected as recently as possible? If you have time today, please stop by so we can review. Thanks!

**Comment by kjones13** [comment]
I just got a 'subscript out of bounds' error message with a dataset I just tried. I'll bring a bunch of datasets to work with.
Your calendar says you're busy until 12. Is this correct?

**Comment by chrlaney** [comment]
​Great - I anticipate that we'll be out early - will let you know.

**Comment by kjones13** [comment]
D10 is entering data right now, I'll pass on the csvs as soon as they are available.

**Comment by chrlaney** [comment]
Latest version is up and running at https://claney.shinyapps.io/neonPhenoSheetGenerator_dev/. Could you test it from there - let me know if any problems? I rotated to landscape to hopefully eliminate problems with text wrapping.

**Comment by chrlaney** [comment]
And please go ahead and add new csv files to repo. Thanks!

**Comment by kjones13** [comment]
I believe the issue repeat headers has been solved now so I'll close this ticket.
